import "./globals.css";
import { Inter, Modak, Space_Grotesk } from "next/font/google";

const mod = Modak({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-puffy",
});
const grot = Space_Grotesk({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-normal",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`bg-[#FF004D] text-white ${mod.variable} ${grot.variable}`}
    >
      <body className={grot.className}>{children}</body>
    </html>
  );
}
